version: '3'
services:
  cstrike:
    container_name: cstrike-server
    image: zarak-a/cstrike-dock:latest
    restart: always
    environment:
      - PORT=27015
      - MAP=de_mirage
      - MAXPLAYERS=32
      - SV_LAN=1
    ports:
      - 27015:27015/udp
      - 27015:27015
    volumes:
      - /path/to/your/server.cfg:/home/steam/cstrike/cstrike/server.cfg
      - /path/to/your/mapcycle.txt:/home/steam/cstrike/cstrike/mapcycle.txt
